### PR TITLE
Use latest irishealth-community because previous one has vanished

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
I wish ISC wouldn't remove containers from their registry without good reason and notification...

### CODE REVIEW

**Comment by grongierisc** [comment]
What you can do is use intersystemsdc who support lastest tag.
 ARG IMAGE=intersystemsdc/iris-community:latest

**Comment by gjsjohnmurray** [comment]
Shall I make that change on this PR?

**Comment by gjsjohnmurray** [comment]
> Shall I make that change on this PR?

Tried it and it didn't work. Googled a bit and learned that :latest doesn't work that way. I think we'll have to continue targeting a specific version.

**Comment by gjsjohnmurray** [comment]
> > Shall I make that change on this PR?
> 
> Tried it and it didn't work. Googled a bit and learned that :latest doesn't work that way. I think we'll have to continue targeting a specific version.

Sorry, I misread your message and overlooked the intersystemsdc bit. Trying that now...

**Pull request merged**
